//! TotK (BNTX `0x00040100`) + new-surface-format coverage.
//!
//! Validates the format batch on real assets (all fixture-gated; skipped
//! when the files are absent — CI ships no game assets):
//! 1. The TotK Title `__Combined.bntx` round-trips **byte-identically**
//!    (version `0x00040100`, 225 textures incl. ASTC_4x4_SRGB + R8G8).
//! 2. Every texture in it deswizzles + decodes (mip 0) to the right dims.
//! 3. HDR's recolored `info_melee` B8G8R8A8 (`0x0c01`) pack round-trips
//!    byte-identically and decodes.
//!
//! Drop the TotK BNTX at `tests/fixtures/bntx/totk_title__Combined.bntx`
//! (e.g. `archive-extract` a `Title*.blarc.zs`) to enable (1)/(2).

use std::path::Path;

use nx_layout_toolbox::bntx::decode::decode_texture_image;
use nx_layout_toolbox::bntx::{read_bntx, write_bntx, AstcBlock, TextureFormat};

const TOTK_TITLE: &str = "tests/fixtures/bntx/totk_title__Combined.bntx";
const HDR_INFO_MELEE: &str = "tests/fixtures/unpacked/\
hdr_ultimate_mods_hdr-assets_ui_layout_info_info_melee_info_melee_layout/timg/__Combined.bntx";

/// Decode every texture (mip 0, layer 0) and assert the decoded image
/// matches the BNTX metadata dimensions + RGBA byte count.
fn assert_all_textures_decode(path: &str) {
    let bytes = std::fs::read(path).expect("read fixture");
    let bntx = read_bntx(&bytes).unwrap_or_else(|e| panic!("{path}: parse: {e}"));
    for (i, tex) in bntx.textures.iter().enumerate() {
        let img = decode_texture_image(&bntx, i, 0, 0, true).unwrap_or_else(|e| {
            panic!(
                "{path}: texture '{}' (#{i}, {}) failed to decode: {e}",
                tex.name(&bntx),
                tex.format.name()
            )
        });
        assert_eq!(
            (img.width, img.height),
            (tex.width, tex.height),
            "{path}: '{}' decoded dims mismatch",
            tex.name(&bntx)
        );
        assert_eq!(
            img.rgba.len(),
            (tex.width * tex.height * 4) as usize,
            "{path}: '{}' RGBA byte count",
            tex.name(&bntx)
        );
    }
}

#[test]
fn totk_title_round_trips_and_decodes() {
    if !Path::new(TOTK_TITLE).exists() {
        eprintln!("skipping TotK BNTX test (drop the fixture at {TOTK_TITLE} to enable)");
        return;
    }
    let bytes = std::fs::read(TOTK_TITLE).expect("read fixture");
    let bntx = read_bntx(&bytes).expect("parse TotK BNTX");

    // Version gate: this is the 0x00040100 container.
    assert_eq!(
        bntx.header.version, 0x0004_0100,
        "expected TotK BNTX version 0x00040100"
    );

    // Byte-identical round-trip — the core discipline. The TotK container
    // is structurally identical to 0x00040000, so the writer reproduces it
    // exactly once the version + formats parse.
    let written = write_bntx(&bntx).expect("write TotK BNTX");
    assert!(
        written == bytes,
        "TotK BNTX round-trip not byte-identical (orig={} rewritten={})",
        bytes.len(),
        written.len()
    );

    // The new formats this batch unlocked must actually be present.
    let has = |pred: &dyn Fn(TextureFormat) -> bool| bntx.textures.iter().any(|t| pred(t.format));
    assert!(
        has(&|f| matches!(f, TextureFormat::Astc { block: AstcBlock::B4x4, srgb: true })),
        "expected an ASTC_4x4_SRGB texture in the TotK fixture"
    );
    assert!(
        has(&|f| f == TextureFormat::R8G8Unorm),
        "expected an R8G8_UNORM texture in the TotK fixture"
    );

    // Every texture (ASTC / R8G8 / BC4 / BC5 / BC1 / RGBA8) decodes.
    assert_all_textures_decode(TOTK_TITLE);

    println!(
        "OK: TotK __Combined.bntx (v0x00040100, {} textures) round-trips + all decode",
        bntx.textures.len()
    );
}

#[test]
fn hdr_bgra8_round_trips_and_decodes() {
    if !Path::new(HDR_INFO_MELEE).exists() {
        eprintln!("skipping HDR B8G8R8A8 test (no fixture at {HDR_INFO_MELEE})");
        return;
    }
    let bytes = std::fs::read(HDR_INFO_MELEE).expect("read fixture");
    let bntx = read_bntx(&bytes).expect("parse HDR info_melee BNTX");

    // The HDR recolor pack uses B8G8R8A8 (0x0c01), with mip chains.
    let bgra_count = bntx
        .textures
        .iter()
        .filter(|t| matches!(t.format, TextureFormat::Bgra8Unorm | TextureFormat::Bgra8UnormSrgb))
        .count();
    assert!(bgra_count > 0, "expected a B8G8R8A8 texture in HDR info_melee");

    // This file was regenerated by a C# tool with a non-canonical internal
    // layout (non-uniform BRTI spacing), so it does NOT round-trip
    // byte-identically — the same known-gap class as
    // `sgpo_one_pane_png_proof`. Validate B8G8R8A8 read/write fidelity via
    // a *semantic* round-trip: write, re-parse, and confirm every
    // texture's format / dims / mips / pixel bytes survive intact.
    let written = write_bntx(&bntx).expect("write HDR BNTX");
    let reparsed = read_bntx(&written).expect("re-parse written HDR BNTX");
    assert_eq!(reparsed.textures.len(), bntx.textures.len());
    for (a, b) in bntx.textures.iter().zip(reparsed.textures.iter()) {
        assert_eq!(a.format, b.format, "format drift for '{}'", a.name(&bntx));
        assert_eq!((a.width, a.height), (b.width, b.height));
        assert_eq!(a.mips_count, b.mips_count);
        assert_eq!(a.array_len, b.array_len);
        assert_eq!(a.channel_swizzle, b.channel_swizzle);
        assert_eq!(
            a.pixel_data(&bntx.brtd),
            b.pixel_data(&reparsed.brtd),
            "pixel data drift for '{}'",
            a.name(&bntx)
        );
    }

    // And every texture (incl. the mipped B8G8R8A8) decodes mip 0.
    assert_all_textures_decode(HDR_INFO_MELEE);
    println!("OK: HDR info_melee B8G8R8A8 semantic round-trip + all decode ({bgra_count} BGRA)");
}
